services:
  db:
    image: postgres:13
    container_name: BioCirV_ETL_db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ../..
      dockerfile: etl_merge/my_etl_project/Dockerfile
    container_name: BioCirV_ETL_app
    env_file:
      - .env
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      - ../..:/app
      - /app/.pixi
    working_dir: /app/etl_merge/my_etl_project
    depends_on:
      db:
        condition: service_healthy
    command: tail -f /dev/null

  prefect-server:
    build:
      context: ../..
      dockerfile: etl_merge/my_etl_project/Dockerfile
    container_name: BioCirV_ETL_prefect_server
    env_file:
      - .env
    ports:
      - "4200:4200"
    volumes:
      - ../..:/app
      - /app/.pixi
      - prefectdata:/root/.prefect
    working_dir: /app/etl_merge/my_etl_project
    depends_on:
      db:
        condition: service_healthy
    command: pixi run prefect server start --host 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  prefect-worker:
    build:
      context: ../..
      dockerfile: etl_merge/my_etl_project/Dockerfile
    container_name: BioCirV_ETL_prefect_worker
    env_file:
      - .env
    volumes:
      - ../..:/app
      - /app/.pixi
    working_dir: /app/etl_merge/my_etl_project
    depends_on:
      prefect-server:
        condition: service_healthy
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    command: pixi run prefect worker start --pool 'biocirv_dev_work_pool'

volumes:
  pgdata:
  prefectdata:
